---
name: python-lsp-server
description: Fork of the python-language-server project, maintained by the Spyder IDE team and the community.
homepage: https://github.com/python-lsp/python-lsp-server
licenses:
  - MIT
languages:
  - Python
categories:
  - LSP

source:
  id: pkg:pypi/python-lsp-server@1.10.0?extra=all
  extra_packages:
    - pylsp-mypy
    - pyls-isort
    - python-lsp-black
    - pyls-memestra
    - pylsp-rope
    - python-lsp-ruff
    - pylsp-path-patcher


schemas:
  lsp: https://raw.githubusercontent.com/python-lsp/python-lsp-server/v{{version}}/pylsp/config/schema.json

bin:
  pylsp: pypi:pylsp
